name: "Test admin frontend"
description: "Run the tests for the React admin frontend"

runs:
  using: "composite"

  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "14"
    - name: Install dependencies
      shell: bash
      working-directory: admin-frontend
      run: npm ci
    - name: Lint
      shell: bash
      working-directory: admin-frontend
      run: npm run lint
    # - name: Test
    #   shell: bash
    #   working-directory: admin-frontend
    #   run: npm run test
